version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: [ '/usr/src/app/entrypoint.sh' ]
    volumes:
      - '.:/usr/src/app'
    ports:
      - 5004:5000
    environment:
      - FLASK_APP=manage.py
      - FLASK_DEBUG=1
      - FLASK_ENV=development
      - APP_SETTINGS=src.config.Config
      - DATABASE_URL=postgresql://postgres:postgres@api-dev-db:5432/api_dev
      - DATABASE_TEST_URL=postgresql://postgres:postgres@api-test-db:5432/api_test
      - SHARED_SECRET_KEY=${SHARED_SECRET_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}

    depends_on:
      - api-dev-db
      - api-test-db
    
  api-dev-db:
    build:
      context: ./src/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  api-test-db:
    build:
      context: ./src/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

